[package]
name = "pdu_io_derive"
version = "0.1.0"
authors = ["Klas <klasa@cs.umu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
